language: php

# branches:
#   only:
#     - master
#     - develop

php:
  - 5.4
  - 5.5

before_script:
    - pear channel-discover pear.phing.info
    - pear install phing/phing
    - phpenv rehash
    - phing install:ci
    - phing tools:start

script: phing ci
