language: php

# branches:
#   only:
#     - master
#     - develop

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
    - pear channel-discover pear.phing.info
    - pear install PHP_CodeSniffer
    - pear install phing/phing
    - phpenv rehash
    - cp build.properties.dist build.properties
    - phing install:ci
    - "php app/console server:run > /dev/null &"
    - "sh -e /etc/init.d/xvfb start"
    - "export DISPLAY=:99.0"
    - "java -jar vendor/selenium/standalone-server/selenium-server-standalone-2.*.jar > /dev/null &"
    - sleep 5

script: phing ci:travis
