# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ["BpaulinUpfitBundle"]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        common_js:
            input:
                - ../vendor/components/jquery/jquery.js
                - ../vendor/twitter/bootstrap/js/bootstrap-affix.js
                - ../vendor/twitter/bootstrap/js/bootstrap-alert.js
                - ../vendor/twitter/bootstrap/js/bootstrap-button.js
                - ../vendor/twitter/bootstrap/js/bootstrap-carousel.js
                - ../vendor/twitter/bootstrap/js/bootstrap-collapse.js
                - ../vendor/twitter/bootstrap/js/bootstrap-dropdown.js
                - ../vendor/twitter/bootstrap/js/bootstrap-modal.js
                - ../vendor/twitter/bootstrap/js/bootstrap-popover.js
                - ../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js
                - ../vendor/twitter/bootstrap/js/bootstrap-tab.js
                - ../vendor/twitter/bootstrap/js/bootstrap-tooltip.js
                - ../vendor/twitter/bootstrap/js/bootstrap-transition.js
                - ../vendor/twitter/bootstrap/js/bootstrap-typeahead.js
        # common_css:
        #     input:
        #         -
