# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    node:           node
    bundles:        ["BpaulinUpfitBundle"]
    filters:
        cssrewrite: ~
        less:
            apply_to: "\.less$"
            node_paths: [/usr/bin/node,%kernel.root_dir%/../node_modules]
    assets:
        common_js:
            input:
                - ../vendor/components/jquery/jquery.js
                - ../vendor/twitter/bootstrap/js/transition.js
                - ../vendor/twitter/bootstrap/js/alert.js
                - ../vendor/twitter/bootstrap/js/button.js
                - ../vendor/twitter/bootstrap/js/carousel.js
                - ../vendor/twitter/bootstrap/js/collapse.js
                - ../vendor/twitter/bootstrap/js/dropdown.js
                - ../vendor/twitter/bootstrap/js/modal.js
                - ../vendor/twitter/bootstrap/js/tooltip.js
                - ../vendor/twitter/bootstrap/js/popover.js
                - ../vendor/twitter/bootstrap/js/scrollspy.js
                - ../vendor/twitter/bootstrap/js/tab.js
                - ../vendor/twitter/bootstrap/js/affix.js
        collection_js:
            input:
                - ../vendor/components/jquery-ui/ui/jquery.ui.core.js
                - ../vendor/components/jquery-ui/ui/jquery.ui.widget.js
                - ../vendor/components/jquery-ui/ui/jquery.ui.mouse.js
                - ../vendor/components/jquery-ui/ui/jquery.ui.sortable.js
                - @BpaulinUpfitBundle/Resources/public/js/collections.js
