# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    node:           /usr/bin/node
    bundles:        ["BpaulinUpfitBundle"]
    filters:
        cssrewrite: ~
        less:
            apply_to: "\.less$"
            bin: %kernel.root_dir%/../node_modules/.bin/lessc
    assets:
        common_js:
            input:
                - ../vendor/components/jquery/jquery.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-affix.js
                - ../vendor/twitter/bootstrap/js/bootstrap-alert.js
                - ../vendor/twitter/bootstrap/js/bootstrap-button.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-carousel.js
                - ../vendor/twitter/bootstrap/js/bootstrap-collapse.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-dropdown.js
                - ../vendor/twitter/bootstrap/js/bootstrap-modal.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-popover.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-tab.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-tooltip.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-transition.js
                # - ../vendor/twitter/bootstrap/js/bootstrap-typeahead.js
        collection_js:
            input:
                - ../vendor/components/jquery-ui/ui/jquery.ui.core.js
                - ../vendor/components/jquery-ui/ui/jquery.ui.widget.js
                - ../vendor/components/jquery-ui/ui/jquery.ui.mouse.js
                - ../vendor/components/jquery-ui/ui/jquery.ui.sortable.js
                - @BpaulinUpfitBundle/Resources/public/js/collections.js
        common_css:
            input:
                - @BpaulinUpfitBundle/Resources/public/less/bootstrap.less
