# Assetic Configuration
assetic:
    filters:
        uglifyjs2:
            apply_to: "\.js$"
            bin: /usr/bin/uglifyjs
            compress: true
            mangle: true
        uglifycss:
            apply_to: ["\.css$", "\.less$"]
            bin: /usr/bin/uglifycss
