# Assetic Configuration
assetic:
    filters:
        uglifyjs2:
            apply_to: "\.js$"
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
            compress: true
            mangle: true
        uglifycss:
            apply_to: ["\.css$", "\.less$"]
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
