imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'BpaulinUpfitBundle:Form:form.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bpaulin\UpfitBundle\Entity\User

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

jms_translation:
    configs:
        BpaulinUpfitBundle:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src/Bpaulin/UpfitBundle]
            output_dir: %kernel.root_dir%/../src/Bpaulin/UpfitBundle/Resources/translations
            ignored_domains: [routes, FOSUserBundle, validators]
            excluded_names: [*TestCase.php, *Test.php, *Context.php]
            excluded_dirs: [cache, data, logs]
            output-format: xliff

jms_i18n_routing:
    default_locale: en
    locales: [de, en, fr, es]
    strategy: prefix_except_default
