<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140127225311 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE user ADD weightObjective INT DEFAULT NULL, ADD weightTolerance INT DEFAULT NULL");
        $this->addSql("CREATE UNIQUE INDEX one_a_day ON weight (dateRecord, user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE user DROP weightObjective, DROP weightTolerance");
        $this->addSql("DROP INDEX one_a_day ON weight");
    }
}
