<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130714175426 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Objective (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, muscle_id INT DEFAULT NULL, will SMALLINT NOT NULL, INDEX IDX_3B6773A2A76ED395 (user_id), INDEX IDX_3B6773A2354FDBB4 (muscle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Objective ADD CONSTRAINT FK_3B6773A2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)");
        $this->addSql("ALTER TABLE Objective ADD CONSTRAINT FK_3B6773A2354FDBB4 FOREIGN KEY (muscle_id) REFERENCES Muscle (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Objective");
    }
}
