<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130718104857 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE workout CHANGE difficulty difficulty SMALLINT DEFAULT NULL, CHANGE difficultyUnit difficultyUnit VARCHAR(20) DEFAULT NULL");
        $this->addSql("ALTER TABLE stage CHANGE difficulty difficulty SMALLINT DEFAULT NULL, CHANGE difficultyUnit difficultyUnit VARCHAR(20) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE stage CHANGE difficulty difficulty SMALLINT NOT NULL, CHANGE difficultyUnit difficultyUnit VARCHAR(20) NOT NULL");
        $this->addSql("ALTER TABLE workout CHANGE difficulty difficulty SMALLINT NOT NULL, CHANGE difficultyUnit difficultyUnit VARCHAR(20) NOT NULL");
    }
}
