<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130717111853 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Intensity (id INT AUTO_INCREMENT NOT NULL, exercise_id INT DEFAULT NULL, muscle_id INT DEFAULT NULL, intensity SMALLINT NOT NULL, INDEX IDX_6B433A31E934951A (exercise_id), INDEX IDX_6B433A31354FDBB4 (muscle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Intensity ADD CONSTRAINT FK_6B433A31E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id)");
        $this->addSql("ALTER TABLE Intensity ADD CONSTRAINT FK_6B433A31354FDBB4 FOREIGN KEY (muscle_id) REFERENCES Muscle (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Intensity");
    }
}
